### ISSUE TITLE
Bugs in neuron.py

### ISSUE THREAD

**Issue by hewh16** [BasBuller/PySNN#16]
I was just trying to test the mlp_example.py . It was supposed  to be easy but ... when the program try to import pysnn/neuron.py at the beginning  of itself, it raised "ValueError(f"Unsupported trace type {update_type}")". It looks like this:

Traceback (most recent call last):
  File "mlp_example.py", line 9, in <module>
    import pysnn.neuron 
  File "/home/hewh16/.local/lib/python3.5/site-packages/pysnn/neuron.py", line 57
    raise ValueError(f"Unsupported trace type {update_type}")
                                                           ^
SyntaxError: invalid syntax

However, in neuron.py, the update_type is already defined to be "linear". So it confused me a lot. Hoping that I can get help from developers. Thanks :)

**Comment by Huizerd** [comment]
This has to do with the version of Python you’re using, which should be 3.6 or above

**Comment by BasBuller** [comment]
Agreed, will make the adjustment in the readme and possibly in the setup.py file. Also closing the issue with that.

**Comment by hewh16** [comment]
Thanks a lot! :)
