### ISSUE TITLE
Updates to Readme: What is a Trace?

### ISSUE THREAD

**Issue by jkiggins** [BasBuller/PySNN#31]
**Is your feature request related to a problem? Please describe.**
Perhaps this is due to a lack of prior knowledge on my part, but I'm not clear on what a trace actually is. This inhibits my understanding of how to format inputs, and inspection of intermediate tensors. Initially I thought the additional R dimension was time, but traces are returned separately. In that case maybe time is handled by the user, and they are passing inputs that either contains spikes in that step, or don't.

**Describe the solution you'd like**
A clear description of what a trace is, and perhaps a simple example. Say a 10x10 image being passed into a single spiking neuron layer, and then the resulting output shapes including traces.

**Describe alternatives you've considered**
Experimentation and diving into the source. I've done both of these, but could go more in depth and possibly find my own answer. 

**Additional context**
I plan to use your library as the main simulation tool for my thesis.

**Comment by Huizerd** [comment]
A trace is actually nothing more than a low-pass filter (moving average) over the output spikes of a neuron, such that you get a signal which is smoother and (more importantly) differentiable. So if you were to encode a 10x10 image as 10x10 spike sequences of say 5 steps (higher pixel values get more spikes, so 255 == [1, 1, 1, 1, 1], while 0 == [0, 0, 0, 0, 0]), and input this to a spiking layer of 10x10 neurons, you would get as trace a 10x10 matrix of the moving average over the output spikes of these neurons.

**Comment by jkiggins-d3** [comment]
Thank you! That makes sense, and the differentiable part is of course important for certain learning rules.

**Comment by jkiggins** [comment]
Thank you! That makes sense, and of course the differentiable piece is important for certain learning rules.
