### ISSUE TITLE
Visualizing NMNIST Events

### ISSUE THREAD

**Issue by tehreemnaqvi** [BasBuller/PySNN#33]
Hi,

I am following your GitHub repository and working on the **Neuromorphic** dataset "**NMNIST**."
Currently, I am struggling to visualize the events, but I got some dimension errors.

My TD dimensions are like "**CHWT**," but I got the error when I tried to visualize using **show_td**.

Below is the code and related error:

![image](https://user-images.githubusercontent.com/38427571/104797455-7cfb7d00-5801-11eb-8045-9bf9a93ee098.png)

![image](https://user-images.githubusercontent.com/38427571/104797461-871d7b80-5801-11eb-93f2-89a7d8eb51d0.png)

Can you please tell me what's wrong with my code? 

Waiting for your response.

Thanks

**Comment by Huizerd** [comment]
Sorry for the late reply, but this repo isn't actively being contributed to anymore. I think [SLAYER](https://github.com/bamsumit/slayerPytorch), which is also largely PyTorch, has working code for N-MNIST. If you're looking for a good, active framework for SNNs, I would recommend [Norse](https://github.com/Norse/Norse). Good luck!
